import type { Scope } from "../config/schema.js";

/**
 * Rules of Engagement + Authorization Letter template (WP6).
 *
 * A ready-to-fill markdown document Cytadel sends the client before testing.
 * Pre-filled from the scope where possible; [BRACKETED] fields are left for the
 * client/tester to complete and sign. Pure/testable.
 */

export interface RoeInput {
  scopeName: string;
  client?: string | null;
  authorizedBy?: string;
  authorizationRef?: string;
  authorizationWindow?: { start: string; end: string } | null;
  environment?: string;
  emergencyContact?: string | null;
  inScopeDomains?: string[];
  inScopeUrls?: string[];
  exclusions?: string[];
  rateLimitRps?: number;
  allowDestructive?: boolean;
}

export function roeInputFromScope(scope: Scope): RoeInput {
  return {
    scopeName: scope.name,
    client: scope.client ?? null,
    authorizedBy: scope.authorized_by,
    authorizationRef: scope.authorization_ref,
    authorizationWindow: scope.authorization_window ?? null,
    environment: scope.environment,
    emergencyContact: scope.emergency_contact ?? null,
    inScopeDomains: scope.in_scope.domains,
    inScopeUrls: scope.in_scope.urls,
    exclusions: [...scope.exclusions.domains, ...scope.exclusions.paths],
    rateLimitRps: scope.rate_limit_rps,
    allowDestructive: scope.allow_destructive,
  };
}

const OR = (v: string | null | undefined, ph: string): string => (v && v.trim() ? v : `[${ph}]`);

/** Render the ROE + Authorization Letter as markdown. */
export function buildRoeTemplate(i: RoeInput): string {
  const list = (arr?: string[]): string => (arr && arr.length ? arr.map((x) => `- ${x}`).join("\n") : "- [NONE SPECIFIED]");
  const win = i.authorizationWindow ? `${i.authorizationWindow.start} → ${i.authorizationWindow.end}` : "[START DATETIME] → [END DATETIME]";
  return `# Rules of Engagement & Authorization Letter

**Engagement:** ${OR(i.scopeName, "ENGAGEMENT NAME")}
**Client:** ${OR(i.client, "CLIENT / ORGANISATION NAME")}
**Testing provider:** Cytadel Security
**Authorization reference (contract / letter id):** ${OR(i.authorizationRef, "CONTRACT-OR-LETTER-ID")}
**Authorized by (client signatory):** ${OR(i.authorizedBy, "NAME, TITLE")}
**Environment:** ${OR(i.environment, "staging | production")}

---

## 1. Authorization

${OR(i.client, "CLIENT")} authorizes Cytadel Security to perform an authorized web-application
penetration test of the systems listed in Section 2, strictly within the
authorization window below. This letter constitutes written permission; testing
outside this window or scope is NOT authorized.

**Authorization window:** ${win}

## 2. Scope

**In-scope domains:**
${list(i.inScopeDomains)}

**In-scope URLs:**
${list(i.inScopeUrls)}

**Explicitly EXCLUDED (never tested):**
${list(i.exclusions)}

## 3. Rules of Engagement

- **Destructive / active-injection testing (SQLi, XSS):** ${i.allowDestructive ? "PERMITTED within window" : "NOT permitted"}.
- **Production testing:** ${i.environment === "production" ? "This engagement targets PRODUCTION — extra confirmation is required and elevated care applies." : "Non-production (staging) — preferred."}
- **Rate limit:** requests are capped at ${i.rateLimitRps ?? "[N]"} req/s to avoid service impact.
- **Permitted testing hours:** [e.g. Mon–Fri 20:00–06:00 client local time, or 24/7].
- **Data handling:** any sensitive data encountered is handled per the signed agreement and is redacted from client-facing reports.
- **Stop conditions:** testing pauses immediately on any sign of service disruption or on client request.

## 4. Emergency contact

During the engagement, the client emergency contact is: ${OR(i.emergencyContact, "NAME — PHONE / EMAIL (24/7)")}
The Cytadel lead is reachable at: [CYTADEL LEAD — PHONE / EMAIL].

## 5. Sign-off

By signing below, the client confirms authority to authorize this testing and
accepts the Rules of Engagement above.

| Role | Name | Signature | Date |
|------|------|-----------|------|
| Client signatory | ${OR(i.authorizedBy, "NAME")} | ______________ | __________ |
| Cytadel lead | [NAME] | ______________ | __________ |

_Generated by Cytadel Sentinel as a ready-to-fill template. Complete all
[BRACKETED] fields and obtain signatures BEFORE any testing begins._
`;
}
